package server

import (
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/TurniXXD/go-rss/internal/database"
	"github.com/TurniXXD/go-rss/utils"
	"github.com/google/uuid"
)

func (cfg *apiConfig) handleCreateUser(w http.ResponseWriter, r *http.Request) {
	type parameters struct {
		Name string `json:"name"`
	}

	decoder := json.NewDecoder(r.Body)

	params := parameters{}
	err := decoder.Decode(&params)
	if err != nil {
		utils.JSONErrorResponse(w, 400, fmt.Sprintf("Error parsing JSON: %v", err))
		return
	}

	// Generated by sqlc
	user, err := apiCfg.DB.CreateUser(r.Context(), database.CreateUserParams{
		ID:        uuid.New(),
		CreatedAt: time.Now().UTC(),
		UpdatedAt: time.Now().UTC(),
		Name:      params.Name,
	})

	if err != nil {
		utils.JSONErrorResponse(w, 400, fmt.Sprintf("Couldn't create user: %v", err))
		return
	}

	utils.JSONResponse(w, 201, mapDbUserToUser(user))
}

func (cfg *apiConfig) handleGetUser(w http.ResponseWriter, r *http.Request, user database.User) {
	utils.JSONResponse(w, 200, mapDbUserToUser(user))
}

func (cfg *apiConfig) handleGetPostsForUser(w http.ResponseWriter, r *http.Request, user database.User) {
	posts, err := cfg.DB.GetPostsForUser(r.Context(), database.GetPostsForUserParams{
		UserID: user.ID,
		Limit:  10,
	})
	if err != nil {
		utils.JSONErrorResponse(w, 400, fmt.Sprintf("Couldn't get posts for user: %v", err))
		return
	}

	utils.JSONResponse(w, 200, mapDbPostsToPosts(posts))
}
